# fly.toml app configuration file for talabasirlaribot

app = 'talabasirlaribot'
primary_region = 'hkg'

[build]

[env]
PORT = "3000" # ✅ Make sure this matches your Express app

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
